# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 
  vmImage: ubuntu-latest

variables:
  - name: Build.BuildId
    value: 0.0.1
jobs:
  - job:
    steps:
    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'
    
    - task: Docker@2
      inputs:
        containerRegistry: 'azure-javaapps-cr'
        repository: 'javaapps'
        command: 'build'
        Dockerfile: '**/psql.dockerfile'

    - script: |
               docker run -e POSTGRES_PASSWORD=admin123 -p 49158:5432 -d javaapps.azurecr.io/titanic-db:$(Build.BuildId)
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean test package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    - task: Docker@2
      inputs:
        containerRegistry: 'azure-javaapps-cr'
        repository: 'titanic-app'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'