apiVersion: v1
data:
  postgressPwd: YWRtaW4xMjM=
kind: Secret
metadata:
  name: dbconf
---
apiVersion: v1
data:
  serverPort: OTA5MA==
  Password: YWRtaW4xMjM=
  Username: cG9zdGdyZXM=
kind: Secret
metadata:
  name: appconf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: titanic-svc
  name: titanic-svc
spec:
  ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: 9090
      nodePort: 30041
  selector:
    app: titanic-app
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: db-svc
  name: db-svc
spec:
  ports:
    - name: titanic-db-port
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: titanic-db
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: titanic-db
  name: titanic-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: titanic-db
  template:
    metadata:
      labels:
        app: titanic-db
    spec:
      containers:
        - image: samaraghu0804/titanic-db
          name: titanic-db
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbconf
                  key: postgressPwd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: titanic-app
  name: titanic-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: titanic-app
  template:
    metadata:
      labels:
        app: titanic-app
    spec:
      containers:
        - image: samaraghu0804/titanic-app:latest
          name: titanic-app
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: appconf
                  key: Username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: appconf
                  key: Password
            - name: SERVER_PORT
              valueFrom:
                secretKeyRef:
                  name: appconf
                  key: serverPort
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db-svc:5432/
